### ISSUE TITLE
Add Send Grid for email notifications

### ISSUE THREAD

**Issue by niss3n** [niss3n/webscraper#4]

**Comment by niss3n** [comment]
docs: https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email

The API Key is already in key vault.

**Comment by jiyoungsin** [comment]
Hey would It be cool for me to solve this issue?

**Comment by jiyoungsin** [comment]
just a heads up that Python3 breaks backwards compatibility. Sendgrid requires Python 2.6, 2.7, 3.4 or 3.5. we can roll back to python 3.5. Its your choice!

**Comment by jiyoungsin** [comment]
If youre open to the idea of other ways of sending email's. I have created a simple solution to your problem using smtplib which is downloaded by default on all macs, however, It comes with configuration variables that must be configured.
https://www.afternerd.com/blog/how-to-send-an-email-using-python-and-smtplib/

**Comment by niss3n** [comment]
Hey Paul!

The nice thing about using SendGrid is that it uses Microsoft's SMPT server
and we can authenticate using an API Key vs a username and password. Plus
you can have it come from any email address you want. I currently have this
working using python 3.8 (might be a recent feature though?) in a different
project. Here is an example of that:

-------------------------------------------------------------------------------------
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

def SendGridEmail():
    print("sending email")
    message = Mail(
        from_name ='John Doe',
        from_email='fromme@fromme.com',
        to_emails='tome@tome.com',
        subject='This is my Subject!',
        html_content='<html code here>')

    token = "#{SendGridApiKey}#" # This will not change, the pipeline uses
token replacement to get the variable.
    sg = SendGridAPIClient(token)
    resonse = sg.send(message)

SendGridEmail()
-------------------------------------------------------------------------------------


Let me know if you have any questions!

-Brad

**Comment by jiyoungsin** [comment]
Would it be okay if I got this task assigned?

**Comment by jiyoungsin** [comment]
Hey niss3n, I too got sendgrid working on my python. even though it says that on their main page. Someone should change that documentation. I noticed my main problem was the google security.

![Screen Shot 2020-10-22 at 11 24 40 PM](https://user-images.githubusercontent.com/44411777/96952938-fa8f4580-14bd-11eb-8695-0403689f40eb.png)

This setting kept denying my log in attempt.

**Comment by jiyoungsin** [comment]
I have just created a pull request regarding sendgrid. Everything works locally, however, when others or yourself use it you might have to sign up for a sendgrid account and use your own API key.

**Comment by niss3n** [comment]
Sendgrid has been integrated and the Issue has been closed.
